workflows:
  cd:
    name: CD Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      android_signing: 
        - weather_keystore
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter pub get
      - name: Build AAB with Flutter
        script: | 
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing: 
      email:
        recipients:
          - dongnqdev@gmail.com
        notify:
          success: true
          failure: true